language: node_js

node_js:
  - '12'

sudo: false

services:
  - docker

branches:
  only:
    - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - '.eslintcache'
    - 'node_modules'

script:
  - yarn
  - yarn lint
  - yarn test
  - yarn ci:coverage
  - yarn build

after_script:
  - docker build -t jinkeli/react-project ./
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push jinkeli/react-project
